import Head from 'next/head'
import Form from '../components/Form'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='container mx-auto py-2' >
        <h1 className='text-4xl text-center font-medium my-5'>Patient Medical History Form</h1>
        <Form />
      </main>

      <footer>

      </footer>
    </>
  )
}
